### ISSUE TITLE
lessons_path --> Clicking into a lesson

### ISSUE THREAD

**Issue by benjaminben** [benjaminben/fullstaff#2]
<b>User Story</b>: ...should be able to click on a thumbnail from the front page and be taken to a page dedicated to the lesson clicked

<b>The Error</b>: PG::UndefinedColumn: ERROR: column upvotes.lesson_id does not exist LINE 1: SELECT "upvotes".\* FROM "upvotes" WHERE "upvotes"."lesson_id... ^ : SELECT "upvotes".\* FROM "upvotes" WHERE "upvotes"."lesson_id" IN ('1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12', '13', '14', '15')

<b>What I've Tried:</b> Google, SO, all the etceteras. I don't understand what upvotes has to do with lessons#show, and even if it does, I'm at the end of my wits trying to find a difference between this code and my code for last week's authentication lab (which also involved vids with upvotes)

**Comment by tambling** [comment]
Your `upvotes` table doesn't have a `lesson_id` column. Make a migration, tell it to `add_reference :upvotes, :lesson_id`, and run that migration with `rake db:migrate`.
